-- Add license_plate column to appointments table
ALTER TABLE public.appointments 
ADD COLUMN IF NOT EXISTS license_plate text;

-- Create appointment_guests table
CREATE TABLE IF NOT EXISTS public.appointment_guests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id bigint REFERENCES public.appointments(id) ON DELETE CASCADE,
    name text NOT NULL,
    cpf text NOT NULL,
    sex text,
    contact text,
    amount numeric DEFAULT 10.00,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add RLS policies for appointment_guests (optional but recommended)
ALTER TABLE public.appointment_guests ENABLE ROW LEVEL SECURITY;

-- Allow users to insert guests for their own appointments
CREATE POLICY "Users can insert guests for their own appointments" 
ON public.appointment_guests FOR INSERT 
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.appointments 
        WHERE id = appointment_guests.appointment_id 
        AND user_id = auth.uid()
    )
);

-- Allow users to view their own appointment guests
CREATE POLICY "Users can view their own appointment guests" 
ON public.appointment_guests FOR SELECT 
USING (
    EXISTS (
        SELECT 1 FROM public.appointments 
        WHERE id = appointment_guests.appointment_id 
        AND user_id = auth.uid()
    )
);

-- Allow admins to view all guests (assuming admin role check logic exists or handled via service role, 
-- but explicit policy is good if admins use client-side fetch)
-- Note: Usually admins bypass RLS or have specific role-based policies. 
-- Adding a basic one for authenticated users with role 'admin' if profiles mapping is standard, 
-- but often admins just use service role in Supabase dashboard. 
-- For safety, let's allow users to read if they own the parent appointment.

