
-- Create system_settings table
CREATE TABLE IF NOT EXISTS system_settings (
    key TEXT PRIMARY KEY,
    value NUMERIC NOT NULL,
    description TEXT
);

-- Insert default values if not exists
INSERT INTO system_settings (key, value, description) VALUES
('price_day_use', 0.00, 'Preço base para Day-use'),
('price_evento', 0.00, 'Preço base para Eventos'),
('price_apartamento', 0.00, 'Preço base para Apartamentos'),
('price_guest', 10.00, 'Preço por convidado'),
('price_fine', 50.00, 'Valor padrão de multa');

-- Create fines table
CREATE TABLE IF NOT EXISTS fines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    amount NUMERIC NOT NULL,
    reason TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    status TEXT DEFAULT 'pending' -- pending, paid
);

-- Enable RLS
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE fines ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Settings: Everyone can read, Only Admin can update
DROP POLICY IF EXISTS "Enable read access for all users" ON system_settings;
CREATE POLICY "Enable read access for all users" ON system_settings FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable update for admins only" ON system_settings;
CREATE POLICY "Enable update for admins only" ON system_settings FOR UPDATE USING (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- Fines: Admins can do everything. Users can read their own.
DROP POLICY IF EXISTS "Enable all access for admins" ON fines;
CREATE POLICY "Enable all access for admins" ON fines FOR ALL USING (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);
DROP POLICY IF EXISTS "Enable read own fines" ON fines;
CREATE POLICY "Enable read own fines" ON fines FOR SELECT USING (
  user_id = auth.uid()
);

-- View for Billing Summary
-- This view aggregates costs per user:
-- 1. Appointment Guest Costs (sum of appointment_guests.amount)
-- 2. Fines (sum of fines.amount where status = 'pending')
-- Note: We are assuming appointment base price isn't stored per-appointment yet, only guest costs are distinct.
-- If user wants base prices to apply to PAST appointments, we'd calculate on the fly. 
-- For now, let's sum guest amounts.

CREATE OR REPLACE VIEW billing_summary AS
SELECT 
    p.id as user_id,
    p.nome_completo,
    p.email,
    p.cpf,
    -- Count Appointments
    (SELECT COUNT(*) FROM appointments a WHERE a.user_id = p.id AND a.status = 'aprovado') as appointments_count,
    -- Sum Guest Costs (from approved appointments)
    COALESCE(
        (SELECT SUM(g.amount) 
         FROM appointment_guests g 
         JOIN appointments a ON a.id = g.appointment_id 
         WHERE a.user_id = p.id AND a.status = 'aprovado')
    , 0) as total_guest_costs,
    -- Sum Fines (pending)
    COALESCE(
        (SELECT SUM(f.amount) 
         FROM fines f 
         WHERE f.user_id = p.id AND f.status = 'pending')
    , 0) as total_fines,
    -- Total Debt
    (
        COALESCE(
            (SELECT SUM(g.amount) 
            FROM appointment_guests g 
            JOIN appointments a ON a.id = g.appointment_id 
            WHERE a.user_id = p.id AND a.status = 'aprovado')
        , 0)
        +
        COALESCE(
            (SELECT SUM(f.amount) 
            FROM fines f 
            WHERE f.user_id = p.id AND f.status = 'pending')
        , 0)
    ) as total_debt
FROM profiles p
WHERE p.role = 'user';
