-- 1. Tabela 'profiles' para armazenar dados de usuários
CREATE TABLE public.profiles (
    id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    email text UNIQUE,
    nome_completo text,
    cpf text UNIQUE,
    telefone text,
    matricula text UNIQUE,
    role text DEFAULT 'user'::text NOT NULL CHECK (role IN ('admin', 'user')),
    status text DEFAULT 'pendente'::text NOT NULL CHECK (status IN ('pendente', 'ativo'))
);
COMMENT ON TABLE public.profiles IS 'Tabela para dados de perfil de usuário, vinculada ao sistema de autenticação.';

-- 2. Tabela 'news' para notícias e comunicados
CREATE TABLE public.news (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text NOT NULL,
    summary text,
    content_html text NOT NULL,
    image_url text
);
COMMENT ON TABLE public.news IS 'Armazena artigos de notícias e comunicados.';

-- 3. Tabela 'gallery' para a galeria de fotos
CREATE TABLE public.gallery (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    image_url text NOT NULL,
    caption text
);
COMMENT ON TABLE public.gallery IS 'Armazena imagens e legendas para a galeria.';

-- 4. Tabela 'partners' para convênios e parcerias
CREATE TABLE public.partners (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    category text,
    benefit_desc text NOT NULL,
    logo_url text
);
COMMENT ON TABLE public.partners IS 'Lista de parceiros e os benefícios oferecidos.';

-- 5. Tabela 'board_members' para membros da diretoria
CREATE TABLE public.board_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    role text NOT NULL,
    photo_url text
);
COMMENT ON TABLE public.board_members IS 'Informações sobre os membros da diretoria.';

-- 6. Habilita RLS e cria políticas "Allow All" para desenvolvimento inicial

-- Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- News
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow ALL for all users" ON public.news FOR ALL USING (true) WITH CHECK (true);

-- Gallery
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow ALL for all users" ON public.gallery FOR ALL USING (true) WITH CHECK (true);

-- Partners
ALTER TABLE public.partners ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow ALL for all users" ON public.partners FOR ALL USING (true) WITH CHECK (true);

-- Board Members
ALTER TABLE public.board_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow ALL for all users" ON public.board_members FOR ALL USING (true) WITH CHECK (true);