-- VIDEO FEED SCHEMA

-- 1. Tabela 'videos'
CREATE TABLE IF NOT EXISTS public.videos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text NOT NULL,
    description text,
    video_url text NOT NULL
);
COMMENT ON TABLE public.videos IS 'Armazena os vídeos para o feed mobile.';

-- 2. Tabela 'video_likes'
CREATE TABLE IF NOT EXISTS public.video_likes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    video_id bigint NOT NULL REFERENCES public.videos(id) ON DELETE CASCADE,
    session_id text NOT NULL -- Identificador anônimo stored no localStorage
);
COMMENT ON TABLE public.video_likes IS 'Armazena likes nos vídeos (anônimo via session_id).';

-- 3. Tabela 'video_comments'
CREATE TABLE IF NOT EXISTS public.video_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    video_id bigint NOT NULL REFERENCES public.videos(id) ON DELETE CASCADE,
    author_name text NOT NULL,
    content text NOT NULL
);
COMMENT ON TABLE public.video_comments IS 'Armazena comentários nos vídeos.';

-- 4. Storage Bucket for Videos
INSERT INTO storage.buckets (id, name, public) VALUES ('videos', 'videos', true) ON CONFLICT (id) DO NOTHING;


-- RLS POLICIES

-- Videos
ALTER TABLE public.videos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public videos are viewable by everyone." ON public.videos;
CREATE POLICY "Public videos are viewable by everyone." ON public.videos FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can manage videos." ON public.videos;
CREATE POLICY "Admins can manage videos." ON public.videos FOR ALL USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- Video Likes
ALTER TABLE public.video_likes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Everyone can view likes." ON public.video_likes;
CREATE POLICY "Everyone can view likes." ON public.video_likes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Everyone can insert likes." ON public.video_likes;
CREATE POLICY "Everyone can insert likes." ON public.video_likes FOR INSERT WITH CHECK (true);

-- Video Comments
ALTER TABLE public.video_comments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Everyone can view comments." ON public.video_comments;
CREATE POLICY "Everyone can view comments." ON public.video_comments FOR SELECT USING (true);

DROP POLICY IF EXISTS "Everyone can insert comments." ON public.video_comments;
CREATE POLICY "Everyone can insert comments." ON public.video_comments FOR INSERT WITH CHECK (true);


-- STORAGE POLICIES
DROP POLICY IF EXISTS "Videos are publicly accessible." ON storage.objects;
CREATE POLICY "Videos are publicly accessible." ON storage.objects FOR SELECT USING (bucket_id = 'videos');

DROP POLICY IF EXISTS "Admins can upload videos." ON storage.objects;
CREATE POLICY "Admins can upload videos." ON storage.objects FOR INSERT WITH CHECK (
    bucket_id = 'videos' AND 
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
);

DROP POLICY IF EXISTS "Admins can delete videos." ON storage.objects;
CREATE POLICY "Admins can delete videos." ON storage.objects FOR DELETE USING (
    bucket_id = 'videos' AND 
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
);
