-- ARQUIVO UNIFICADO DE SCHEMA - ASFUS MOBILE
-- Use este arquivo para criar toda a estrutura do banco de dados no novo projeto Supabase.

-- ==============================================================================
-- PARTE 1: TABELAS BASE (Profiles, News, Gallery, Partners, Board Members)
-- ==============================================================================

-- 1. Tabela 'profiles'
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    email text UNIQUE,
    nome_completo text,
    cpf text UNIQUE,
    telefone text,
    matricula text UNIQUE,
    role text DEFAULT 'user'::text NOT NULL CHECK (role IN ('admin', 'user')),
    status text DEFAULT 'pendente'::text NOT NULL CHECK (status IN ('pendente', 'ativo'))
);
COMMENT ON TABLE public.profiles IS 'Tabela para dados de perfil de usuário, vinculada ao sistema de autenticação.';

-- 2. Tabela 'news'
CREATE TABLE IF NOT EXISTS public.news (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text NOT NULL,
    summary text,
    content_html text NOT NULL,
    image_url text
);
COMMENT ON TABLE public.news IS 'Armazena artigos de notícias e comunicados.';

-- 3. Tabela 'gallery'
CREATE TABLE IF NOT EXISTS public.gallery (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    image_url text NOT NULL,
    caption text
);
COMMENT ON TABLE public.gallery IS 'Armazena imagens e legendas para a galeria.';

-- 4. Tabela 'partners'
CREATE TABLE IF NOT EXISTS public.partners (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    category text,
    benefit_desc text NOT NULL,
    logo_url text
);
COMMENT ON TABLE public.partners IS 'Lista de parceiros e os benefícios oferecidos.';

-- 5. Tabela 'board_members'
CREATE TABLE IF NOT EXISTS public.board_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    role text NOT NULL,
    photo_url text
);
COMMENT ON TABLE public.board_members IS 'Informações sobre os membros da diretoria.';

-- Habilita RLS (Safe to run multiple times, works if table exists)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_members ENABLE ROW LEVEL SECURITY;

-- Políticas de segurança (DROP before CREATE to avoid conflicts)

-- Profiles
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile." ON public.profiles;
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- News
DROP POLICY IF EXISTS "Allow ALL for all users" ON public.news;
CREATE POLICY "Allow ALL for all users" ON public.news FOR ALL USING (true) WITH CHECK (true);

-- Gallery
DROP POLICY IF EXISTS "Allow ALL for all users" ON public.gallery;
CREATE POLICY "Allow ALL for all users" ON public.gallery FOR ALL USING (true) WITH CHECK (true);

-- Partners
DROP POLICY IF EXISTS "Allow ALL for all users" ON public.partners;
CREATE POLICY "Allow ALL for all users" ON public.partners FOR ALL USING (true) WITH CHECK (true);

-- Board Members
DROP POLICY IF EXISTS "Allow ALL for all users" ON public.board_members;
CREATE POLICY "Allow ALL for all users" ON public.board_members FOR ALL USING (true) WITH CHECK (true);


-- ==============================================================================
-- PARTE 2: APPOINTMENTS (Agendamentos)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.appointments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    booking_date date NOT NULL,
    status text DEFAULT 'pendente'::text NOT NULL CHECK (status IN ('pendente', 'aprovado', 'rejeitado')),
    feedback text
);

COMMENT ON TABLE public.appointments IS 'Armazena as solicitações de agendamento de espaços pelos associados.';
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own appointments." ON public.appointments;
CREATE POLICY "Users can view their own appointments." ON public.appointments FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can create appointments for themselves." ON public.appointments;
CREATE POLICY "Users can create appointments for themselves." ON public.appointments FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can manage all appointments." ON public.appointments;
CREATE POLICY "Admins can manage all appointments." ON public.appointments FOR ALL USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');


-- ==============================================================================
-- PARTE 3: EVENTS (Eventos)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    image_url text,
    event_date date NOT NULL,
    location text
);

COMMENT ON TABLE public.events IS 'Armazena informações sobre eventos.';
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can manage all events." ON public.events;
CREATE POLICY "Admins can manage all events." ON public.events FOR ALL USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

DROP POLICY IF EXISTS "Public events are viewable by everyone." ON public.events;
CREATE POLICY "Public events are viewable by everyone." ON public.events FOR SELECT USING (true);


-- ==============================================================================
-- PARTE 4: STORAGE (Buckets)
-- ==============================================================================

-- Criação dos buckets (ignora se já existir)
INSERT INTO storage.buckets (id, name, public) VALUES ('avatars', 'avatars', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('images', 'images', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('documents', 'documents', true) ON CONFLICT (id) DO NOTHING;

-- Policies for Storage (Drop first)
DROP POLICY IF EXISTS "Avatar images are publicly accessible." ON storage.objects;
CREATE POLICY "Avatar images are publicly accessible." ON storage.objects FOR SELECT USING (bucket_id = 'avatars');

DROP POLICY IF EXISTS "Anyone can upload an avatar." ON storage.objects;
CREATE POLICY "Anyone can upload an avatar." ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'avatars');

DROP POLICY IF EXISTS "Images are publicly accessible." ON storage.objects;
CREATE POLICY "Images are publicly accessible." ON storage.objects FOR SELECT USING (bucket_id = 'images');

DROP POLICY IF EXISTS "Anyone can upload an image." ON storage.objects;
CREATE POLICY "Anyone can upload an image." ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'images');

DROP POLICY IF EXISTS "Documents are publicly accessible." ON storage.objects;
CREATE POLICY "Documents are publicly accessible." ON storage.objects FOR SELECT USING (bucket_id = 'documents');

DROP POLICY IF EXISTS "Anyone can upload a document." ON storage.objects;
CREATE POLICY "Anyone can upload a document." ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'documents');

