CREATE TABLE public.events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    image_url text,
    event_date date NOT NULL,
    location text
);

COMMENT ON TABLE public.events IS 'Armazena informações sobre eventos.';

-- Habilita RLS
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

-- Regras de Segurança:
-- 1. Admins podem gerenciar todos os eventos.
CREATE POLICY "Admins can manage all events." ON public.events
    FOR ALL USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- 2. Public pode ver todos os eventos.
CREATE POLICY "Public events are viewable by everyone." ON public.events
    FOR SELECT USING (true);
