CREATE TABLE public.appointments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    booking_date date NOT NULL,
    status text DEFAULT 'pendente'::text NOT NULL CHECK (status IN ('pendente', 'aprovado', 'rejeitado')),
    feedback text
);

COMMENT ON TABLE public.appointments IS 'Armazena as solicitações de agendamento de espaços pelos associados.';

-- Habilita RLS
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

-- Regras de Segurança:
-- 1. Usuários podem ver seus próprios agendamentos.
CREATE POLICY "Users can view their own appointments." ON public.appointments
    FOR SELECT USING (auth.uid() = user_id);

-- 2. Usuários podem criar agendamentos para si mesmos.
CREATE POLICY "Users can create appointments for themselves." ON public.appointments
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 3. Admins podem ver, atualizar e deletar qualquer agendamento.
CREATE POLICY "Admins can manage all appointments." ON public.appointments
    FOR ALL USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');
